# Generated by Django 5.2.5 on 2025-08-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datalog',
            fields=[
                ('TIMESTAMP', models.DateTimeField(primary_key=True, serialize=False, verbose_name='TimeStamp')),
                ('SERVO_MOTOR_RAW', models.IntegerField(verbose_name='Servo Motor Reading')),
                ('SERVO_MOTOR_SCA', models.FloatField(verbose_name='Servo Motor Angle')),
                ('SERVO_RAW', models.IntegerField(verbose_name='Sensor Reading')),
                ('SERVO_SCA', models.FloatField(verbose_name='Sensor Distance')),
                ('ARDUINO_RPI_STATUS', models.BooleanField(verbose_name='Serial Connection Status')),
                ('ARDUINO_STATUS', models.BooleanField(verbose_name='Status Arduino')),
                ('RPI_STATUS', models.BooleanField(verbose_name='Status Raspberry')),
            ],
        ),
    ]
